<a href="https://colab.research.google.com/github/kingfaluk/KCCA_FC/blob/main/Week2_Assignment/Week2_Ecommerce_Analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sqlite3
import pandas as pd

try:
    if 'conn' in locals() and conn:
        conn.close()
except:
    pass

conn = sqlite3.connect('ecommerce.db')
cursor = conn.cursor()

In [ ]:
cursor.execute(
    """
    create table IF NOT EXISTS customers(
    customer_id integer primary key,
    customer_name text not null,
    customer_email text not null unique,
    customer_password text not null
    )
    """
)

cursor.execute(
    """
    create table IF NOT EXISTS products(
    product_id integer primary key,
    product_name text not null,
    product_description text,
    product_price real not null,
    product_image text
    )
    """
)

cursor.execute(
    """
    create table IF NOT EXISTS orders(
    order_id integer primary key,
    customer_id integer not null,
    product_id integer not null,
    quantity integer not null,
    order_date text not null,
    order_total real not null,
    foreign key(customer_id) references customers(customer_id) on delete cascade,
    foreign key(product_id) references products(product_id) on delete cascade
    )
    """
)

conn.commit()

In [ ]:
customr_list=[
    (1, 'faluk', 'faluk@kodataltd.org', 'faluk123'),
    (2, 'Alex', 'alex@kodataltd.org', 'alex123'),
    (3, 'Vanessa', 'vanessa@kodataltd.org', 'vanessa123'),
    (4, 'Wes', 'wes@kodataltd.org', 'wes123'),
    (5, 'Jonan', 'jonan@kodataltd.org', 'jonan123'),
    (6, 'Anita', 'anita@kodataltd.org', 'anita123')
]

product_list=[
    (1, 'Laptop', '15 inch laptop', 650.00, 'laptop.jpg'),
    (2, 'Phone', 'Android smartphone', 350.00, 'phone.jpg'),
    (3, 'Headphones', 'Wireless headphones', 80.00, 'headphones.jpg'),
    (4, 'Keyboard', 'USB keyboard', 45.00, 'keyboard.jpg'),
    (5, 'Monitor', '24 inch monitor', 220.00, 'monitor.jpg'),
    (6, 'Mouse', 'Wireless mouse', 30.00, 'mouse.jpg')
]

order_list=[
    (1, 1, 1, 1, '2026-08-20', 650.00),
    (2, 2, 2, 2, '2026-08-20', 700.00),
    (3, 3, 3, 2, '2026-08-21', 160.00),
    (4, 1, 5, 1, '2026-08-22', 220.00),
    (5, 4, 4, 3, '2026-08-22', 135.00),
    (6, 5, 6, 4, '2026-08-23', 120.00),
    (7, 6, 2, 1, '2026-08-24', 350.00),
    (8, 3, 5, 2, '2026-08-24', 440.00),
    (9, 1, 3, 1, '2026-08-25', 80.00)
]

cursor.executemany(
    """
    insert or replace into customers(customer_id, customer_name, customer_email, customer_password)
    values (?,?,?,?)
    """,
    customr_list
)

cursor.executemany(
    """
    insert or replace into products(product_id, product_name, product_description, product_price, product_image)
    values (?,?,?,?,?)
    """,
    product_list
)

cursor.executemany(
    """
    insert or replace into orders(order_id, customer_id, product_id, quantity, order_date, order_total)
    values (?,?,?,?,?,?)
    """,
    order_list
)

conn.commit()

## Basic Data Exploration

In [ ]:
query = """
select c.customer_name, count(o.order_id) as total_orders
from customers c
left join orders o on c.customer_id = o.customer_id
group by c.customer_id, c.customer_name
order by total_orders desc
"""

pd.read_sql_query(query, conn)

  customer_name  total_orders
0         faluk             3
1       Vanessa             2
2          Alex             1
3           Wes             1
4         Jonan             1
5         Anita             1

## High-Value Customers

In [ ]:
query = """
with customer_spending as (
    select c.customer_id, c.customer_name, sum(o.order_total) as total_spent
    from customers c
    join orders o on c.customer_id = o.customer_id
    group by c.customer_id, c.customer_name
)
select customer_name, total_spent
from customer_spending
where total_spent > 500
order by total_spent desc
"""

df_high_value = pd.read_sql_query(query, conn)
df_high_value

  customer_name  total_spent
0         faluk        950.0
1          Alex        700.0
2       Vanessa        600.0

## Product Popularity

In [ ]:
query = """
select p.product_name, coalesce(sum(o.quantity), 0) as total_quantity_sold
from products p
left join orders o on p.product_id = o.product_id
group by p.product_id, p.product_name
order by total_quantity_sold desc
"""

pd.read_sql_query(query, conn)

  product_name  total_quantity_sold
0        Mouse                    4
1        Phone                    3
2   Headphones                    3
3     Keyboard                    3
4      Monitor                    3
5       Laptop                    1

## Running Total of Revenue

In [ ]:
query = """
select order_date,
       daily_revenue,
       sum(daily_revenue) over(order by order_date) as running_total
from (
    select order_date, sum(order_total) as daily_revenue
    from orders
    group by order_date
)
order by order_date
"""

pd.read_sql_query(query, conn)

   order_date  daily_revenue  running_total
0  2026-08-20         1350.0         1350.0
1  2026-08-21          160.0         1510.0
2  2026-08-22          355.0         1865.0
3  2026-08-23          120.0         1985.0
4  2026-08-24          790.0         2775.0
5  2026-08-25           80.0         2855.0

## Export High-Value Customers

In [ ]:
df_high_value.to_csv('high_value_customers.csv', index=False)
df_high_value

  customer_name  total_spent
0         faluk        950.0
1          Alex        700.0
2       Vanessa        600.0

In [ ]:
from google.colab import files
files.download('high_value_customers.csv')

## MongoDB Atlas

In [ ]:
!pip install pymongo

Collecting pymongo
  Downloading pymongo-4.17.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (10 kB)
Collecting dnspython<3.0.0,>=2.6.1 (from pymongo)
  Downloading dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Downloading pymongo-4.17.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 28.9 MB/s eta 0:00:00
Downloading dnspython-2.8.0-py3-none-any.whl (331 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 29.6 MB/s eta 0:00:00
Installing collected packages: dnspython, pymongo
Successfully installed dnspython-2.8.0 pymongo-4.17.0

In [ ]:
import pymongo
from getpass import getpass
from urllib.parse import quote_plus
#magodb user password:Us7YqQ7dGpvDRsGY

password = quote_plus(getpass('MongoDB password: '))
client = pymongo.MongoClient(
    f"mongodb+srv://kiberufaluk6_db_user:{password}@cluster0.ixlmifv.mongodb.net/?appName=Cluster0"
)

db = client["ecommerce_nosql"]
reviews = db["reviews"]

client.admin.command("ping")

MongoDB password: ··········

{'ok': 1}

In [ ]:
review_list = [
    {"product_id": 1, "username": "faluk", "rating": 5, "tags": ["fast", "good quality"]},
    {"product_id": 2, "username": "Alex", "rating": 4, "tags": ["good camera", "affordable"]},
    {"product_id": 5, "username": "Vanessa", "rating": 3, "tags": ["clear display", "average"]}
]

reviews.insert_many(review_list)

In [ ]:
for review in reviews.find({"rating": {"$gte": 4}}):
    print(review)